Register google
juliocesar1235/yuva-frontend pull request #19
Opened 2022-11-27 01:33 UTC by ada112

2022-11-27 19:05 UTC, juliocesar1235 requested changes
Te deje unos comments pao, pero en general se ve cool 💯

2022-11-27 19:05 UTC, juliocesar1235 commented on src/app/app.module.ts
> +          provider: new GoogleLoginProvider('390325317211-qvh4viqaqvas45nui5pmdp6m9c56mhfh.apps.googleusercontent.com'),
Ve si puedes poner este en un archivo .env pao, porque veo que trae un token que debe de ser oculto

2022-11-27 19:05 UTC, juliocesar1235 commented on src/app/components/signup-contractor/signup-contractor.component.ts
> +      this.router.navigate(['/profile/contractor/' + this.userResponse], {queryParams:{data: this.userResponse}})
Esto si jala? no se si cambiaste el back para que regresara solo el id

2022-11-27 21:14 UTC, ada112 commented on src/app/components/signup-contractor/signup-contractor.component.ts
> +      this.router.navigate(['/profile/contractor/' + this.userResponse], {queryParams:{data: this.userResponse}})
Si cambie el back para que traiga el id segun yo si jala.

2022-11-27 21:14 UTC, ada112 commented on src/app/app.module.ts
> +          provider: new GoogleLoginProvider('390325317211-qvh4viqaqvas45nui5pmdp6m9c56mhfh.apps.googleusercontent.com'),
Ok. Lo hago en un rato

2022-11-28 22:24 UTC, juliocesar1235 approved these changes, later dismissed

2022-11-28 22:24 UTC, juliocesar1235 commented on src/environments/environment.prod.ts
> +  googleProvider: '390325317211-qvh4viqaqvas45nui5pmdp6m9c56mhfh.apps.googleusercontent.com',
creo que este archivo iria en el gitignore pao, para que no salga el token

2022-11-28 23:01 UTC, ada112 commented on src/environments/environment.prod.ts
> +  googleProvider: '390325317211-qvh4viqaqvas45nui5pmdp6m9c56mhfh.apps.googleusercontent.com',
Ya arregle lo de git ignore

2022-11-28 23:01 UTC, juliocesar1235 submitted a review, later dismissed
Crack 💯

2022-11-28 23:06 UTC, juliocesar1235 approved these changes

2022-11-28 23:08 UTC, merged