Vista confirmacion
juliocesar1235/yuva-frontend pull request #20
Opened 2022-11-28 22:27 UTC by akarinaat

2022-11-28 22:32 UTC, juliocesar1235 reviewed
Te deje unos comments Karina, se ve ve bien nomas hay que hacer esos pequeños cambios 👌

2022-11-28 22:32 UTC, juliocesar1235 commented on src/app/app-routing.module.ts
> +import { VistaServicioContratarComponent } from './components/vista-servicio-contratar/vista-servicio-contratar.component';
Aca puedes cambiarlo mejor a AllocationComponent, igual a los demas archivos para tener todo en ingles 👌

2022-11-28 22:32 UTC, juliocesar1235 commented on src/app/app.module.ts
> +import { VistaServicioContratarComponent } from './components/vista-servicio-contratar/vista-servicio-contratar.component';
igual aca el nombre

2022-11-28 22:32 UTC, juliocesar1235 commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.ts
> +            this.employee = response
aca no siempre traera el id del empleado porque solo lo regresara cuando un empleado lo haya confirmado, para eso hay que hacer que sea opcional y agregar una condicion en el componente

2022-11-28 22:32 UTC, juliocesar1235 commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.html
> +      <p class="card-text mt-4 ms-4" *ngIf="employee"><b>Nombre del empleado:</b> {{ employee.firstName}} {{employee.lastName}}</p>
estos no siempre estaran disponibles asi que hay que agregar un if para cuando no tenga id y ponerle "buscando empleado"

2022-11-29 01:24 UTC, akarinaat commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.html
> +      <p class="card-text mt-4 ms-4" *ngIf="employee"><b>Nombre del empleado:</b> {{ employee.firstName}} {{employee.lastName}}</p>
Ahí está el ngIf :p lol

2022-11-29 02:31 UTC, juliocesar1235 requested changes
solo sería cambiar los nombres de los archivos y le damos merge

2022-11-29 02:31 UTC, juliocesar1235 commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.ts
> +  selector: 'app-vista-servicio-contratar',
Aca hay que cambiar todos los archivos a usar el mismo nombre de la clase, que es Allocation

2022-11-29 02:31 UTC, juliocesar1235 commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.html
> +<app-header></app-header>
igual aca, no hay que usar nombres en español

2022-11-29 02:31 UTC, juliocesar1235 commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.spec.ts
> +import { AllocationComponent } from './vista-servicio-contratar.component';
igual aca

2022-11-29 02:31 UTC, juliocesar1235 commented on src/app/app-routing.module.ts
> +import { AllocationComponent } from './components/vista-servicio-contratar/vista-servicio-contratar.component';
esta bien el nombre del componente pero también hay que cambiar el nombre de los archivos

2022-11-29 16:21 UTC, akarinaat commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.ts
> +  selector: 'app-vista-servicio-contratar',
listo

2022-11-29 16:23 UTC, juliocesar1235 requested changes

2022-11-29 16:23 UTC, juliocesar1235 commented on src/app/app-routing.module.ts
> -
aca esta bien pero recuerda que tiene que tener el .component al final de cada nombre del archivo

2022-11-29 16:23 UTC, juliocesar1235 commented on src/app/app.module.ts
> +import { AllocationComponent } from './components/allocation/allocation';
también aquí

2022-11-29 16:26 UTC, akarinaat commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.html
> +<app-header></app-header>
no hay nada en español aquí

2022-11-29 16:39 UTC, juliocesar1235 commented on src/app/components/vista-servicio-contratar/vista-servicio-contratar.component.html
> +<app-header></app-header>
me referia al nombre del archivo :)

2022-12-01 01:31 UTC, juliocesar1235 approved these changes

2022-12-01 01:31 UTC, merged