Pantalla listado favoritos contratista
juliocesar1235/yuva-frontend pull request #6
Opened 2022-10-22 16:28 UTC by ada112

2022-10-27 02:19 UTC, juliocesar1235 reviewed
Te deje algunos comments pao, lo demas se ve todo al 100. Solo dame chance de hacer los cambios al figma para que podamos hacer el cambio del diseño

2022-10-27 02:19 UTC, juliocesar1235 commented on src/app/app-routing.module.ts
> +  { path: 'profile/favorite', component: FavoriteServiceComponent },
aca debe de ser profile/contractor/favorites, como el empleado no tendría esta vista podemos hacer la distinción

2022-10-27 02:19 UTC, juliocesar1235 commented on src/app/components/favorite-service/favorite-service.component.html
> +      <div class="col-md-8">
también aca creo que podemos mejorar el diseño del listado para que no ocupe tanto espacio 1 solo servicio. aca dejame trabajar en el figma para que lo podamos cambiar 🙏

2022-10-28 02:07 UTC, ada112 commented on src/app/app-routing.module.ts
> +  { path: 'profile/favorite', component: FavoriteServiceComponent },
Listo

2022-10-28 02:07 UTC, ada112 commented on src/app/components/favorite-service/favorite-service.component.html
> +      <div class="col-md-8">
Listo

2022-11-02 05:21 UTC, juliocesar1235 commented
Aca hay que resolver los conflicts pao y le damos merge 👌

2022-11-02 05:22 UTC, juliocesar1235 requested changes
se ve al 100 solo hay que resolver los conflicts para que nos deje mergear

2022-11-03 22:09 UTC, juliocesar1235 approved these changes
Te quedo cool pao! 💯

2022-11-03 22:39 UTC, merged