Componentes dinamicos vista listado servicios
juliocesar1235/yuva-frontend pull request #8
Opened 2022-10-26 01:49 UTC by ada112

2022-10-27 02:28 UTC, juliocesar1235 requested changes
Te deje 1 comentario pao, todo lo demas esta perfect 💯

2022-10-27 02:28 UTC, juliocesar1235 commented on src/app/components/service-card/service-card.component.html
> +        <img src={{service.Avatar}} class="square img-fluid mx-auto d-block" width="200">
aca la imagen no sale porque se encuentra en service.media.serviceAvatar

2022-10-28 01:44 UTC, ada112 commented on src/app/components/service-card/service-card.component.html
> +        <img src={{service.Avatar}} class="square img-fluid mx-auto d-block" width="200">
ya quedo

2022-10-28 02:07 UTC, ada112 commented on src/app/components/service-card/service-card.component.html
> +        <img src={{service.Avatar}} class="square img-fluid mx-auto d-block" width="200">
Listo

2022-11-02 05:10 UTC, juliocesar1235 approved these changes
Buen trabajo pao! Te quedo cool :D

2022-11-02 17:32 UTC, merged