Consumir end point
juliocesar1235/yuva-frontend pull request #9
Opened 2022-10-29 21:26 UTC by akarinaat

Está listo hasta lo que hay en en back

2022-11-02 05:35 UTC, juliocesar1235 requested changes
Se ve muy cool como tienes implementado para la parte del id del usuario en la vista y como haces las peticiones 👌  solo te deje algunos comentarios antes de mezclar

2022-11-02 05:35 UTC, juliocesar1235 commented on src/app/components/employee-profile/employee-profile.component.html
> +            <div class="card-body">
aca hay que hacerle display a toda la información del usuario, esto es todo lo que un usuario por el momento tiene en la base de datos
<img width="630" alt="Captura de Pantalla 2022-11-01 a la(s) 23 30 23" src="https://user-images.githubusercontent.com/16786905/199405896-1db6f6b4-8e38-4d1b-800c-c0c67190dc46.png">

2022-11-02 05:35 UTC, juliocesar1235 commented on src/app/components/employee-profile/employee-profile.component.html
> +                    <b>Sub-categoría</b>
hay que quitar este campo ya que solo tenemos contemplado por el momento a la categoria

2022-11-02 05:35 UTC, juliocesar1235 commented on src/app/components/employee-profile/employee-profile.component.html
> +            <h2>{{service.name}}</h2>
Aca también podríamos agregar el avatar del servicio, lo puedes sacar desde _service.media.serviceAvatar_

2022-11-07 16:50 UTC, juliocesar1235 requested changes
Se ven buenos los cambios Karina! Ahí te deje algunos comments 👌

2022-11-07 16:50 UTC, juliocesar1235 commented on src/app/components/contractor-profile/contractor-profile.component.ts
> +      .get("http://localhost:3000/yuva-api/services/" + "63466d59f5cea1401ec15dbc")
Aqui no debemos de hardcodear el id mejor hay que quitarlo para no tener esa llamada y cambiale el nombre a loadAllocations para que este más ligado a lo que vamos a tener proximamente 💯

2022-11-07 16:50 UTC, juliocesar1235 commented on src/app/components/contractor-profile/contractor-profile.component.ts
> +    console.log("user:", this.user)
Quita este console log para tratar de no mostrar toda la info de algún usuario en la consola. Esta bien agregarlos para correrlo en local pero ya al momento de hacer el MR hay que quitarlo

2022-11-07 16:50 UTC, juliocesar1235 commented on src/app/components/employee-profile/employee-profile.component.ts
> +  usersInfo = [{
Me gusto este diccionario para las traducciones, es muy buena idea! El punto de mejora que te diría es que veo que repites algunas llaves y valores con el perfil del contractor. Intenta ver si puedes exportar en una variable o constante las que se repiten y solo las importas en cualquiera de los dos archivos.

2022-11-07 16:50 UTC, juliocesar1235 commented on src/app/components/contractor-profile/contractor-profile.component.ts
> +        this.user["rigtDOB"] = new Date(this.user["dateOfBirth"]).toLocaleDateString()
podríamos ponerle un nombre más descriptivo, como formattedDOB

2022-11-07 16:50 UTC, juliocesar1235 commented on src/app/components/employee-profile/employee-profile.component.ts
> +        this.user["rigtDOB"] = new Date(this.user["dateOfBirth"]).toLocaleDateString()
Igual que la corrección de arriba

2022-11-08 03:02 UTC, juliocesar1235 requested changes
Ya solo te deje un comentario, también hay que arreglar los conflictos para poder mezclar

2022-11-08 03:02 UTC, juliocesar1235 commented on src/app/components/contractor-profile/contractor-profile.component.html
> +                    <p>{{user[category.propertyName]}}</p>
Aca no debe de aparecer la label si no tiene esa información el usuario

2022-11-09 16:41 UTC, akarinaat commented on src/app/components/contractor-profile/contractor-profile.component.html
> +                    <p>{{user[category.propertyName]}}</p>
Corregido en perfil contratista

2022-11-09 16:54 UTC, juliocesar1235 approved these changes
Buen trabajo Karina! ya quedo listo el PR 💯

2022-11-09 21:44 UTC, merged